### ISSUE TITLE
Dashboard says "See ROBOT Report for details." but those details are not in the report HTML.

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/OBO-Dashboard#81]
On the OBI page of the dashboard <http://dashboard.obofoundry.org/dashboard/obi/dashboard.html> under "Textual Definitions" it says "3 missing definitions. See ROBOT Report for details." (This is a known problem with OBI that we are fixing <https://github.com/obi-ontology/obi/issues/1553>.) But when I click the link below for the ROBOT report <http://dashboard.obofoundry.org/dashboard/obi/robot_report.html>, the HTML version is truncated and I only see two warnings. The TSV version of the report is longer, but I don't see the textual definition there either.

I understand that the reports get long, but ideally at least these 3 missing definitions would be included in the report.

I think it would be better to have a "View Report" link in the "Textual Definition" row if there are any problems. The easy thing would be to make it the same link to the ROBOT report. It would be even nicer to have a view that's just for Textual Definition problems.

**Comment by anitacaron** [comment]
I can't see this issue for this case anymore. But I'll check if it's possible to download the complete ROBOT report.

**Comment by anitacaron** [comment]
I found another case where the [report HTML for MF](https://dashboard.obofoundry.org/dashboard/mf/robot_report.html) shows less information than the one in the TSV file.

The ROBOT report summary says
![Screenshot 2023-12-20 at 11 57 10](https://github.com/OBOFoundry/OBO-Dashboard/assets/2208124/ea37213a-278a-4d35-8370-e015ce9c2a99)


but

![Screenshot 2023-12-20 at 11 54 37](https://github.com/OBOFoundry/OBO-Dashboard/assets/2208124/02056fed-8f57-4925-ad0e-c4ccfcfb1102)

It's because of the whitespace in the definition.

This is also adding the text definition as a type of error

![Screenshot 2023-12-20 at 12 01 39](https://github.com/OBOFoundry/OBO-Dashboard/assets/2208124/92ba7abd-eff0-423c-988f-4fbd4d136dcc)
